print("Please key in four numbers: ")
print("> ", end = "")
s = input()
num1 = int(s)
print("> ", end = "")
s = input()
num2 = int(s)
print("> ", end = "")
s = input()
num3 = int(s)
print("> ", end = "")
s = input()
num4 = int(s)
total = num1 + num2 + num3 + num4
print("Total: " + str(total))
